services:
  - type: web
    name: anonxmusic-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m AnonXMusic
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: LOGGER_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: STRING_SESSION2
        sync: false
      - key: STRING_SESSION3
        sync: false
      - key: STRING_SESSION4
        sync: false
      - key: STRING_SESSION5
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: DURATION_LIMIT
        value: "60"
      - key: AUTO_LEAVING_ASSISTANT
        value: "False"
      - key: PLAYLIST_FETCH_LIMIT
        value: "25"
      - key: TG_AUDIO_FILESIZE_LIMIT
        value: "104857600"
      - key: TG_VIDEO_FILESIZE_LIMIT
        value: "1073741824"
      - key: SUPPORT_CHANNEL
        value: "https://t.me/FallenAssociation"
      - key: SUPPORT_CHAT
        value: "https://t.me/DevilsHeavenMF"
